#!/usr/bin/env python3

"""
Created on 18 Apr 2018

@author: Bruno Beloff (bruno.beloff@southcoastscience.com)

DESCRIPTION
The csv_logger_conf utility is used to specify the filesystem path to the log files generated by csv_logger. It also
specifies the csv_logger behaviour when the volume becomes full: if delete-oldest is true, the oldest logs are
removed to make space, if false, then logging stops.

Note that the logging process(es) must be restarted for changes to take effect.

SYNOPSIS
csv_logger_conf.py [-r ROOT_PATH] [-o DELETE_OLDEST] [-v]

EXAMPLES
./csv_logger_conf.py -r /Users/bruno/SCS/logs -o 1

DOCUMENT EXAMPLE - INPUT
{"tag": "scs-ap1-6", "rec": "2018-04-04T14:50:27.641+00:00", "val": {"hmd": 59.6, "tmp": 23.8}}

DOCUMENT EXAMPLE - OUTPUT
tag,rec,val.hmd,val.tmp
scs-ap1-6,2018-04-04T14:50:38.394+00:00,59.7,23.8

SEE ALSO
scs_dev/csv_logger
"""

import sys

from scs_core.csv.csv_logger_conf import CSVLoggerConf
from scs_core.data.json import JSONify
from scs_core.sys.filesystem import Filesystem

from scs_host.sys.host import Host

from scs_mfr.cmd.cmd_csv_logger_conf import CmdCSVLoggerConf


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------
    # cmd...

    cmd = CmdCSVLoggerConf()

    if cmd.verbose:
        print(cmd, file=sys.stderr)
        sys.stderr.flush()


    # ----------------------------------------------------------------------------------------------------------------
    # resources...

    # check for existing document...
    conf = CSVLoggerConf.load(Host)


    # ----------------------------------------------------------------------------------------------------------------
    # run...

    if cmd.set():
        if conf is None and not cmd.is_complete():
            print("csv_logger_conf: No configuration is present. You must therefore set all fields:", file=sys.stderr)
            cmd.print_help(sys.stderr)
            exit(1)

        root_path = conf.root_path if cmd.root_path is None else cmd.root_path
        delete_oldest = conf.delete_oldest if cmd.delete_oldest is None else cmd.delete_oldest

        try:
            Filesystem.mkdir(root_path)
        except PermissionError:
            print("csv_logger_conf: You do not have permission to create that directory.", file=sys.stderr)
            exit(1)


        conf = CSVLoggerConf(root_path, delete_oldest)
        conf.save(Host)

    if conf:
        print(JSONify.dumps(conf))
